### PR TITLE
Add two new death statistics

### PR DESCRIPTION
**Pull request by exscape**
Hi!  
I wanted a mod to track how many times I've died the current gaming session, especially in the current screen/room, i.e. a value that resets to 0 on screen transitions.  
I couldn't find a mod that showed these stats, but this one was close, so I added the functionality.

I don't know if you're interested in adding it to the released mod or not, but I figured I'd open a PR and check!

### CODE REVIEW

**Comment by exscape** [comment]
I also added two timers, that I didn't add to the PR as they might not really fit with the mod's purpose. They show the time since the last reset of the new stats, i.e. time since last level load, and time since last transition, shown in mm:ss or h:mm:ss formats (the latter if it's >= 1 hour).

I pushed that in a separate branch [here](https://github.com/exscape/DeathTracker/commit/3d232a2e3f32ba48abeff6e2f69173f0efab38f2) just in case.

**Comment by FakeDomi** [comment]
Sure, I'd pull it in.
I just noticed that I haven't put a license here - I intend to put the standard MIT license. Do you agree to put your contributions under the same terms?

**Comment by exscape** [comment]
Absolutely, that's fine. You don't really need to put any copyright to me at all, just add a LICENSE file with your name. :)

**Comment by FakeDomi** [comment]
Alright, got the new counters in. Also did a bit of polishing work on the mod now. I'm not sure whether I want more timers in the mod yet, I'll give it some more thought.

**Comment by exscape** [comment]
My fork has diverged a bit more by now, especially after your polishing, but I don't really intend to share the mod (and perhaps not the code either) publicly. By now it saves per-screen death stats and play time to SaveData, but you can only view those stats while you're on that screen, so it's only really useful while playing through a difficult section -- as I've been doing for a while now, finishing up all the B-sides, and then perhaps C-sides.  
Regarding polishing, it's also rather hacky, but good enough for me to play with at least :)

**Pull request merged**
